 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mss.mirage.util;
import com.mss.mirage.util.DataSourceDataProvider;
import com.constantcontact.components.contacts.ContactList;
import com.constantcontact.components.emailcampaigns.EmailCampaignRequest;
import com.constantcontact.components.emailcampaigns.EmailCampaignResponse;
import com.constantcontact.components.emailcampaigns.MessageFooter;
import com.constantcontact.components.emailcampaigns.SentToContactList;
import com.constantcontact.components.emailcampaigns.schedules.EmailCampaignSchedule;
import com.constantcontact.exceptions.component.ConstantContactComponentException;
import com.constantcontact.exceptions.service.ConstantContactServiceException;
import com.constantcontact.services.contactlists.ContactListService;
import com.constantcontact.services.contacts.ContactService;
import com.constantcontact.services.emailcampaigns.EmailCampaignService;
import com.constantcontact.services.emailcampaigns.schedule.EmailCampaignScheduleService;
import com.constantcontact.util.RawApiRequestError;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import com.mss.mirage.util.DateUtility;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Date;
import java.text.DateFormat;
import java.text.Format;
import java.text.ParseException;

import java.text.SimpleDateFormat;

/**
 *
 * @author miracle
 */
public class ConstantContact {
    public static void main(String[] args) throws ConstantContactServiceException, ConstantContactComponentException, ServiceLocatorException, ParseException, ParseException{
       doSendNominationsExtendedMail("SAP Conference","India","2017-03-01","2017-03-29","2017-03-25","2017-03-26");
    }
     public static void doSendNominationsExtendedMail(String eventName,String eventLocation,String eventFromDate,String eventToDate,String nominationEndDatePrev,String nominationEndDateCurrent) throws ConstantContactServiceException, ConstantContactComponentException, ServiceLocatorException, ParseException, ParseException, ParseException{
        try{
               EmailCampaignService ecs = new EmailCampaignService("dd48ad18-32cd-43ff-95db-6dae1119bb3f","9u6qt7fjruawny4c6eevbxvp");

                EmailCampaignRequest emailReq = new EmailCampaignRequest();


                ContactService cs = new ContactService("dd48ad18-32cd-43ff-95db-6dae1119bb3f", "9u6qt7fjruawny4c6eevbxvp");
                
                ContactListService cls = new ContactListService("dd48ad18-32cd-43ff-95db-6dae1119bb3f", "9u6qt7fjruawny4c6eevbxvp");
                List<ContactList> cl = cls.getLists(null);
                          List<SentToContactList> scl = new ArrayList();

            Map locationMap=new HashMap();
            locationMap.put("1","Miracle City");  
            locationMap.put("2","Onsite");
            
                Iterator entries = locationMap.entrySet().iterator();
                while (entries.hasNext()) {
                     Map.Entry entry = (Map.Entry) entries.next();
                for (int i = 0; i < cl.size(); i++) {
                    if (cl.get(i).getName().trim().equalsIgnoreCase((String)entry.getValue())) {
                        String ltid = cl.get(i).getId();
                          SentToContactList stcl = new SentToContactList();
                        stcl.setId(ltid);
                          scl.add(stcl);
                    }
                }

                }
 String datetime = new SimpleDateFormat("ddMMMyyyy_hh_mm_ss_SSSa").format(new java.util.Date());
                emailReq.setName("Conference_Nominations_Extended_"+datetime);
                emailReq.setSubject(" Nominations Extended ");
                emailReq.setFromEmail("kolasantu@gmail.com");
                emailReq.setFromName("Santhosh");
                emailReq.setReplyToEmail("kolasantu@gmail.com");
                emailReq.setStatus("DRAFT");
                emailReq.setPermissionReminderEnabled(false);
              //  emailReq.setPermissionReminderText("PermissionReminderText");
                emailReq.setViewAsWebpageEnabled(false);

                emailReq.setGreetingName("FIRST_NAME");
                emailReq.setGreetingSalutations("Hello");
               // emailReq.set
                emailReq.setGreetingString("Dear");
             StringBuffer htmlText=new StringBuffer();
             
             
htmlText.append(" <html xmlns='http://www.w3.org/1999/xhtml' class='gr__newsletters-2017-vnallamalla_c9users_io'><head>");
htmlText.append("       <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>");
htmlText.append("       <meta name='viewport' content='width=device-width, initial-scale=1'>");
htmlText.append("       <meta http-equiv='X-UA-Compatible' content='IE=edge'>");
htmlText.append("       <meta name='format-detection' content='telephone=no'>");
htmlText.append("       <title>Nominations Opened</title>");
htmlText.append("       <style>");
htmlText.append("          @import url('https://fonts.googleapis.com/css?family=Montserrat:400,700');");
htmlText.append("          @import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i');");
htmlText.append("          html{width: 100%;}");
htmlText.append("          body{");
htmlText.append("          width: 100%;");
htmlText.append("          background-color: #ffffff;");
htmlText.append("          margin:0; padding:0;");
htmlText.append("          -webkit-text-size-adjust:none;");
htmlText.append("          -ms-text-size-adjust:none;");
htmlText.append("          -webkit-font-smoothing: ;");
htmlText.append("          mso-margin-top-alt:0px;");
htmlText.append("          mso-margin-bottom-alt:0px;");
htmlText.append("          mso-padding-alt: 0px 0px 0px 0px;}");
htmlText.append("          div, p, a, li, td { -webkit-text-size-adjust:none; }");
htmlText.append("          #outlook a {padding:0;}");
htmlText.append("          p,h1,h2,h3,h4{ margin-top:0; margin-bottom:0; padding-top:0; padding-bottom:0;}");
htmlText.append("          table{");
htmlText.append("          mso-table-lspace:0pt;");
htmlText.append("          mso-table-rspace:0pt;");
htmlText.append("          }");
htmlText.append("          table td {border-collapse: collapse;}");
htmlText.append("          span.preheader{display: none;font-size: 1px; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;}");
htmlText.append("          .googlefix {width: 280px!important; text-align:center!important; min-width:0px!important}");
htmlText.append("          a {outline:none;}");
htmlText.append("          a {text-decoration: none;}");
htmlText.append("          a img {border:none;}");
htmlText.append("          .image_fix {display:block;}");
htmlText.append("          .ReadMsgBody { width: 100%;}");
htmlText.append("          .ExternalClass {width: 100%;}");
htmlText.append("          .ExternalClass,");
htmlText.append("          .ExternalClass p,");
htmlText.append("          .ExternalClass span,");
htmlText.append("          .ExternalClass font,");
htmlText.append("          .ExternalClass td,");
htmlText.append("          .ExternalClass div {");
htmlText.append("          line-height: 100%;}");
htmlText.append("          img{");
htmlText.append("          -ms-interpolation-mode:bicubic;}");
htmlText.append("          p {");
htmlText.append("          margin:0 !important;");
htmlText.append("          padding:0 !important;}");
htmlText.append("          .button:hover {filter: brightness(120%);}");
htmlText.append("          @media only screen and (max-width: 600px)");
htmlText.append("          {");
htmlText.append("          body{width:100% !important;}");
htmlText.append("          .container           {width:100% !important; min-width:100% !important;}");
htmlText.append("          .container-wrap      {display:inline-block !important; width:100% !important; height:auto !important; border-radius:0 !important;}");
htmlText.append("          .image-container     {width: 100% !important; height: auto !important; }");
htmlText.append("          .disable             {display: none !important;}");
htmlText.append("          .enable              {display: inline !important;}");
htmlText.append("          .padding-top-10      {padding-top: 10px !important;}");
htmlText.append("          .padding-top-20      {padding-top: 20px !important;}");
htmlText.append("          .padding-top-30      {padding-top: 30px !important;}");
htmlText.append("          .padding-top-40      {padding-top: 40px !important;}");
htmlText.append("          .padding-top-60      {padding-top: 60px !important;}");
htmlText.append("          .padding-bottom-10   {padding-bottom: 10px !important;}");
htmlText.append("          .padding-bottom-20   {padding-bottom: 20px !important;}");
htmlText.append("          .padding-bottom-30   {padding-bottom: 30px !important;}");
htmlText.append("          .padding-bottom-40   {padding-bottom: 40px !important;}");
htmlText.append("          .padding-bottom-60   {padding-bottom: 60px !important;}");
htmlText.append("          .padding-none        {padding:0  !important;}");
htmlText.append("          .text                {width:90% !important; text-align:center !important;}");
htmlText.append("          .text-on-bg          {width:90% !important; text-align:center !important;}");
htmlText.append("          .text-center         {text-align: center !important;}");
htmlText.append("          .text-right          {text-align: right !important;}");
htmlText.append("          .text-left           {text-align: left !important;}");
htmlText.append("          .text-white          {color: #ffffff !important;}");
htmlText.append("          .background-cover    {background-size: cover !important;}");
htmlText.append("          .background-cover-percent    {background-size: 100% 79% !important;}");
htmlText.append("          .background-contain  {background-size: contain !important;}");
htmlText.append("          .background-auto     {background-size: auto !important;}");
htmlText.append("          .background-center   {background-position: center center !important;}");
htmlText.append("          .background-none     {background-image: none !important;}");
htmlText.append("          .border-none         {border:0 !important;}");
htmlText.append("          .border-white        {border-color: #ffffff !important;}");
htmlText.append("          }");
htmlText.append("          @media only screen and (max-width: 451px)");
htmlText.append("          {");
htmlText.append("          body {width:100% !important;}");
htmlText.append("          .container           {width:100% !important; min-width:100% !important;}");
htmlText.append("          .container-wrap      {display:inline-block !important; width:100% !important; height:auto !important; border-radius:0 !important;}");
htmlText.append("          }");
htmlText.append("          @media only screen and (max-width: 341px)");
htmlText.append("          {");
htmlText.append("          body {width:100%!important;}");
htmlText.append("          .container           {width:100% !important; min-width:100% !important;}");
htmlText.append("          .container-wrap      {display:inline-block !important; width:100% !important; height:auto !important; border-radius:0 !important;}");
htmlText.append("          }");
htmlText.append("       </style>");
htmlText.append("    </head>");
htmlText.append("    <body marginwidth='0' marginheight='0' style='margin-top: 0; margin-bottom: 0; padding-top: 0; padding-bottom: 0; width: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;' offset='0' topmargin='0' leftmargin='0' data-gr-c-s-loaded='true'>");
htmlText.append("       <div class='parentOfBg'></div>");
htmlText.append("       <div id='edit_link' class='hidden' style='display: none; left: 88px; top: 27956px;'>");
htmlText.append("          <!-- Close Link -->");
htmlText.append("          <div class='close_link'></div>");
htmlText.append("          <!-- Edit Link Value -->");
htmlText.append("          <input type='text' id='edit_link_value' class='createlink' placeholder='Your URL'>");
htmlText.append("          <!-- Change Image Wrapper-->");
htmlText.append("          <div id='change_image_wrapper' style='display: none;'>");
htmlText.append("             <!-- Change Image Tooltip -->");
htmlText.append("             <div id='change_image'>");
htmlText.append("                <!-- Change Image Button -->");
htmlText.append("                <p id='change_image_button'>Change &nbsp; <span class='pixel_result'></span></p>");
htmlText.append("             </div>");
htmlText.append("             <!-- Change Image Link Button -->");
htmlText.append("             <input type='button' value='' id='change_image_link'>");
htmlText.append("             <!-- Remove Image -->");
htmlText.append("             <input type='button' value='' id='remove_image'>");
htmlText.append("          </div>");
htmlText.append("          <!-- Tooltip Bottom Arrow-->");
htmlText.append("          <div id='tip'></div>");
htmlText.append("       </div>");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='navigation-6' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='navigation-6'>");
htmlText.append("          <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#ffffff;' bgcollor='#ffffff' data-bgcolor='nav-6-bg'>");
htmlText.append("                      <table width='600' align='center' class='container' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <!-- margin -->");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='20' width='1' style='font-size: 1px; line-height: 20px; height:20px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center'>");
htmlText.append("                                  <table width='600' align='center' class='container' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                     <tbody>");
htmlText.append("                                        <tr>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <th width='140' align='left' class='container-wrap' valign='top' style='vertical-align: top;'>");
htmlText.append("                                                                               <table align='center' cellpadding='0' cellspacing='0'>");
htmlText.append("                                                                                  <tbody>");
htmlText.append("                                                                                     <tr>");
htmlText.append("                                                                                        <td width='160' align='center' valign='top'>");
htmlText.append("                                                                                           <table width='100%' align='center' cellpadding='0' cellspacing='0'>");
htmlText.append("                                                                                              <tbody>");
htmlText.append("                                                                                                 ");
htmlText.append("                                                                                                 <tr>");
htmlText.append("                                                                                                    <td align='center' valign='top' style='line-height: 0px !important;'>");
htmlText.append("                                                                                                       <a style='text-decoration: none; display: block;' href='http://www.miraclesoft.com/' target='blank'>");
htmlText.append("                                                                                                       <img src='http://www.miraclesoft.com/images/newsletters/miracle-logo-dark.png' alt='logo' width='100%' style='width: 100%; max-width: 100%;'>");
htmlText.append("                                                                                                       </a>");
htmlText.append("                                                                                                    </td>");
htmlText.append("                                                                                                 </tr>");
htmlText.append("                                                                                              </tbody>");
htmlText.append("                                                                                           </table>");
htmlText.append("                                                                                        </td>");
htmlText.append("                                                                                     </tr>");
htmlText.append("                                                                                  </tbody>");
htmlText.append("                                                                               </table>");
htmlText.append("                                                                                  </th>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <th width='320' align='right' class='container-wrap' valign='top' style='vertical-align: top;'>");
htmlText.append("                                              <table width='320' align='right' class='container' border='0' cellpadding='0' cellspacing='0' style='width:320px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                 <!-- margin -->");
htmlText.append("                                                 <tbody>");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='center' height='1' width='1' style='font-size: 1px; line-height: 1px; height:1px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='right'>");
htmlText.append("                                                          <table width='auto' align='right' class='container' border='0' cellpadding='0' cellspacing='0' style='width:autopx; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                             <tbody>");
htmlText.append("                                                                <tr>");
htmlText.append("                                                                   <td align='center'>");
htmlText.append("                                                                      <table width='auto' align='center' class='' border='0' cellpadding='0' cellspacing='0' style='border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                                         <tbody><tr>");
htmlText.append("                               <td align='center' height='15'>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                                                                            <tr>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th align='center' height='1' width='4' style='font-size: 1px; line-height: 1px; width:4px;'>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                               <th style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #000000; font-weight:400; text-transform: uppercase; letter-spacing: 0.05em;'>");
htmlText.append("                                                                                  <a href='http://www.miraclesoft.com/company/' target='blank' style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #000000; font-weight:600; text-transform: uppercase; letter-spacing: 0.05em;' data-size='nav-6-link-size' data-min='9' data-max='40' data-color='nav-6-link-color' mc:edit='nav-6-link-2'>");
htmlText.append("                                                                                     <multiline>About us |</multiline>");
htmlText.append("                                                                                  </a>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th align='center' height='1' width='4' style='font-size: 1px; line-height: 1px; width:4px;'>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                               <th style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #000000; font-weight:400; text-transform: uppercase; letter-spacing: 0.05em;'>");
htmlText.append("                                                                                  <a href='http://www.miraclesoft.com/services/' target='blank' style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #000000; font-weight:600; text-transform: uppercase; letter-spacing: 0.05em;' data-size='nav-6-link-size' data-min='9' data-max='40' data-color='nav-6-link-color' mc:edit='nav-6-link-3'>");
htmlText.append("                                                                                     <multiline> Our Services |</multiline>");
htmlText.append("                                                                                  </a>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th align='center' height='1' width='4' style='font-size: 1px; line-height: 1px; width:4px;'>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                               <th style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #232527; font-weight:600; text-transform: uppercase; letter-spacing: 0.05em;'>");
htmlText.append("                                                                                  <a href='http://www.miraclesoft.com/contact/' target='blank' style='text-align:center; font-family: oPen sans; font-size:12px; line-height: 20px; text-decoration: none; color: #232527; font-weight:600; text-transform: uppercase; letter-spacing: 0.05em;' data-size='nav-6-signUp-size' data-min='9' data-max='40' data-color='nav-6-signUp-color' mc:edit='nav-6-signUp-4'>");
htmlText.append("                                                                                     <multiline>Contact us</multiline>");
htmlText.append("                                                                                  </a>");
htmlText.append("                                                                               </th>");
htmlText.append("                                                                               <!-- link -->");
htmlText.append("                                                                            </tr>");
htmlText.append("                                                                         </tbody>");
htmlText.append("                                                                      </table>");
htmlText.append("                                                                   </td>");
htmlText.append("                                                                </tr>");
htmlText.append("                                                             </tbody>");
htmlText.append("                                                          </table>");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='center' height='18' width='1' style='font-size: 1px; line-height: 18px; height:18px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                 </tbody>");
htmlText.append("                                              </table>");
htmlText.append("                                           </th>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                        </tr>");
htmlText.append("                                     </tbody>");
htmlText.append("                                  </table>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                </tr>");
htmlText.append("              </tbody>");
htmlText.append("       </table>");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='navigation-margin' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='navigation-margin'>");
htmlText.append("             <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#ffffff;' bgcollor='#ffffff' data-bgcolor='navigation-margin-bg'>");
htmlText.append("                      <table width='600' align='center' class='container' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='20' width='1' style='font-size: 1px;line-height: 10px;height: 10px;'>&nbsp;<img editable='' src='http://www.stampready.net/dashboard/editor/user_uploads/zip_uploads/2017/01/10/sEkx1pYXVQlW2njoMKzJbLeA/StampReady/img/spacer.png' alt='spacer' width='1' height='1'>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                </tr>");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append("       <div class='parentOfBg'></div>");
htmlText.append("       <table align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='text-block-1'>");
htmlText.append("           <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#f8f8f8;' data-bgcolor='txt-blck-1-bg'>");
htmlText.append("                      <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <!-- margin -->");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='35' width='1' style='font-size: 1px; line-height: 35px; height:35px;'>");
htmlText.append("                                  &nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align: center;font-family: 'Open Sans' , sans-serif;font-size: 25px;line-height: 20px;text-decoration: none;color: #444444;font-weight:700;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color'>");
htmlText.append("                                  <multiline>Nominations Opened</multiline>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 25px;height: 25px;'>");
htmlText.append("                                  &nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center'>");
htmlText.append("                                  <table width='60' height='2' align='center' border='0' cellpadding='0' cellspacing='0' style='width:60px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; background-color: #232527' data-bgcolor='team-6-line-color'>");
htmlText.append("                                     <tbody>");
htmlText.append("                                        <tr>");
htmlText.append("                                           <td align='center' height='2' width='40' style='font-size: 2px; line-height: 2px; width:40px;'><img src='http://www.stampready.net/dashboard/editor/user_uploads/zip_uploads/2017/01/10/sEkx1pYXVQlW2njoMKzJbLeA/StampReady/img/spacer.png' alt='spacer' width='40' height='2'></td>");
htmlText.append("                                        </tr>");
htmlText.append("                                     </tbody>");
htmlText.append("                                  </table>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                </tr>");
htmlText.append("                ");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append("       ");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='text-block-1' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='text-block-1'>");
htmlText.append("            <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#f8f8f8;' bgcollor='#f8f8f8' data-bgcolor='txt-blck-1-bg'>");
htmlText.append("                      <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px; line-height: 25px; height:25px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align:left;font-family: 'Open Sans' , sans-serif;font-size: 14px;line-height: 20px;text-decoration: none;color: #444444;font-weight:400;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color' mc:edit='txt-blck-1-text-1'>");
//htmlText.append("                                  <multiline><b>[Name],</b>");
htmlText.append("                                  <multiline><b>Hello Team,</b>");
htmlText.append("                                  </multiline>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                </tr>");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append("       ");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='text-block-1' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='text-block-1'>");
htmlText.append("             <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#f8f8f8;' bgcollor='#f8f8f8' data-bgcolor='txt-blck-1-bg'>");
htmlText.append("                      <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align:justify; font-family: 'Open Sans' , sans-serif; font-size:14px; line-height: 20px; text-decoration: none; color: #444444; font-weight:400;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color' mc:edit='txt-blck-1-text-1'>");
htmlText.append("                                  <multiline>We are happy to inform you that nominations have been opened for <b>"+eventName+"</b> which is happening at <b>"+eventLocation+"</b> from <b>"+eventFromDate+"</b> to <b>"+eventToDate+"</b>. </multiline>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            ");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("             <td align='left' class='button-width'>");
htmlText.append("                                                                                  <table align='left' class='display-button' bgcolor='#232527' style='border-radius: 5px;' data-bgcolor='Header-Butn-BG'>");
htmlText.append("                                                                                     <tbody>");
htmlText.append("                                                                                        <tr>");
htmlText.append("                                                                                           <td align='left' class='MsoNormal' style='color: #ffffff; font-family:'Open Sans'; font-size: 15px; font-weight: 700; padding: 2px 12px;  border-radius: 5px; line-height: 25.5px;' data-color='Header-Butn-Txt' data-size='Header-Butn-Txt' data-min='12' data-max='33'><a href='#' target='blank' class='' style='color:#ffffff; text-decoration:none;' data-color='Header-Butn-Txt'>Nominate Now!</a></td>");
htmlText.append("                                                                                        </tr>");
htmlText.append("                                                                                     </tbody>");
htmlText.append("                                                                                  </table>");
htmlText.append("                                                                                   ");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               ");
htmlText.append("           </tr>");
htmlText.append("                <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align:left; font-family: 'Open Sans' , sans-serif; font-size:14px; line-height: 20px; text-decoration: none; color: #232527; font-weight:400;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color' mc:edit='txt-blck-1-text-1'>");
htmlText.append("                                  <multiline><i><b><span style='color:#ef4048;;'>Note:</span></b> Your application must be submitted before <b>"+nominationEndDateCurrent+"</b></i></multiline>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                           </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                </tr>");
htmlText.append("             </tbody>");
htmlText.append("       </table>");
htmlText.append(" ");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='text-block-1' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='text-block-1'>");
htmlText.append("          <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#f8f8f8;' bgcollor='#f8f8f8' data-bgcolor='txt-blck-1-bg'>");
htmlText.append("                      <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <!-- margin -->");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            <!-- text -->");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align:justify; font-family: 'Open Sans' , sans-serif; font-size:14px; line-height: 20px; text-decoration: none; color: #444444; font-weight:400;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color' mc:edit='txt-blck-1-text-1'>");
htmlText.append("                                  <multiline>Once you have submitted the application our team will go through the submissions and nominate a selected set to attend the event. For more information please reach out to <a href='mailto:partnerships@miraclesoft.com'><span style='color:#00aae7;'>partnerships@miraclesoft.com</span></a> (or) visit <a href='http://www.miraclesoft.com/conferencenominations' target='blank'><span style='color:#00aae7;'>www.miraclesoft.com/conferencenominations.</span></a>");
htmlText.append(" </multiline>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- text -->");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            ");
htmlText.append("                            <!-- margin -->");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                  ");
htmlText.append("                </tr>");
htmlText.append("                ");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append(" ");
htmlText.append("      <table mc:repeatable='layout' mc:hideable='' mc:variant='text-block-1' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='text-block-1'>");
htmlText.append("         ");
htmlText.append("             <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#f8f8f8;' bgcollor='#f8f8f8' data-bgcolor='txt-blck-1-bg'>");
htmlText.append("                      <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <!-- margin -->");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='25' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            <!-- text -->");
htmlText.append("                            <tr>");
htmlText.append("                               <td style='text-align:left; font-family: 'Open Sans' , sans-serif; font-size:13px; line-height: 20px; text-decoration: none; color: #444444; font-weight:400;' data-size='txt-blck-1-text-size' data-min='9' data-max='40' data-color='txt-blck-1-text-color' mc:edit='txt-blck-1-text-1'>");
htmlText.append("                                  <i><multiline>Thanks &amp; Regards<br>Partnership Team<br>");
htmlText.append(" ");
htmlText.append(" Phone : (248)-412-0430<br>");
htmlText.append(" Email : <a href='mailto:partnerships@miraclesoft.com'><span style='color:#232527;'>partnerships@miraclesoft.com</span></a>");
htmlText.append(" </multiline></i>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- text -->");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='46' width='1' style='font-size: 1px; line-height: 46px; height:46px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- margin -->");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                   <!--[if gte mso 9]>");
htmlText.append("                   </v:textbox>");
htmlText.append("                   </v:rect>");
htmlText.append("                   <![endif]-->");
htmlText.append("                </tr>");
htmlText.append("                <!--[if (gte mso 9)|(IE)]>");
htmlText.append("          </table>");
htmlText.append("          <![endif]-->");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append("       <table mc:repeatable='layout' mc:hideable='' mc:variant='footer-5' align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='margin:0 auto; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px; max-width:680px;' data-module='footer-5'>");
htmlText.append("             <tbody>");
htmlText.append("                <tr>");
htmlText.append("                   <td align='center' style='width:100%; height:100%; background-color:#ffffff;' bgcollor='#ffffff' data-bgcolor='footer-5-bg'>");
htmlText.append("                      <table width='600' align='center' class='container' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                         <!-- margin -->");
htmlText.append("                         <tbody>");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center' height='35' width='1' style='font-size: 1px;line-height: 15px;height: 15px;'>&nbsp;");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                            <!-- margin -->");
htmlText.append("                            <tr>");
htmlText.append("                               <td align='center'>");
htmlText.append("                                  <table width='600' align='center' class='text' border='0' cellpadding='0' cellspacing='0' style='width:600px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                     <tbody>");
htmlText.append("                                        <tr>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <th width='360' align='left' class='container-wrap' valign='top' style='vertical-align: top;'>");
htmlText.append("                                              <table width='360' align='left' class='container' border='0' cellpadding='0' cellspacing='0' style='width:360px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                 <!-- rights -->");
htmlText.append("                                                 <tbody>");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td class='text-left' style='vertical-align:top;text-align:left;font-family: 'Open Sans', sans-serif;font-size:13px;padding-top: 5px;line-height: 20px;text-decoration: none;color: #444444;font-weight: 400;' data-size='footer-5-rights-size' data-min='9' data-max='40' data-color='footer-5-rights-color' mc:edit='footer-5-rights-1.1'>");
htmlText.append("                                                          <multiline>© Copyrights 2017 | Miracle Software Systems, Inc.</multiline>");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- rights -->");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='center' height='13' width='1' style='font-size: 1px; line-height: 13px; height:13px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <!-- unsub -->");
htmlText.append("                                                    <!-- unsub -->");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='center' height='39' width='1' style='font-size: 1px;line-height: 20px;height: 20px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                 </tbody>");
htmlText.append("                                              </table>");
htmlText.append("                                           </th>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                           <th width='280' align='right' class='container-wrap' valign='top' style='vertical-align: top;'>");
htmlText.append("                                              <table width='280' align='right' class='container' border='0' cellpadding='0' cellspacing='0' style='width:280px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                 <!-- margin -->");
htmlText.append("                                                 <tbody>");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td class='disable' align='center' height='5' width='1' style='font-size: 1px; line-height: 5px; height:5px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='right'>");
htmlText.append("                                                          <table width='135' align='right' class='container' border='0' cellpadding='0' cellspacing='0' style='width:135px; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border: 0px;'>");
htmlText.append("                                                             <!-- icons -->");
htmlText.append("                                                             <tbody>");
htmlText.append("                                                                <tr>");
htmlText.append("                                                                   <td align='left'>");
htmlText.append("                                                                      <table style='border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;border: 0px;' align='left' border='0' cellpadding='0' cellspacing='0' width='auto'>");
htmlText.append("                                                                         <tbody>");
htmlText.append("                                                                            <tr>");
htmlText.append("                                                                               <th>");
htmlText.append("                                                                                     <a href='https://www.facebook.com/miracle45625/' target='blank' style='color:#ef4048; text-decoration: none;'><img src='http://www.miraclesoft.com/images/newsletters/facebook1.png' width='20' height='20' alt='#' style='display:block; vertical-align:middle;'></a>   </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <td align='center' height='1' width='10' style='font-size: 1px; line-height: 1px; width:10px;'>");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th>");
htmlText.append("                                                                                 <a href='https://plus.google.com/+Team_MSS' target='blank' style='color:#ef4048; text-decoration: none;'><img src='http://www.miraclesoft.com/images/newsletters/googleplus1.png' width='20' height='20' alt='#' style='display:block; vertical-align:middle;'></a>     </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <td align='center' height='1' width='10' style='font-size: 1px; line-height: 1px; width:10px;'>");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th>");
htmlText.append("                                                                                      <a href='https://www.linkedin.com/company/miracle-software-systems-inc' target='blank' style='color:#ef4048; text-decoration: none;'><img src='http://www.miraclesoft.com/images/newsletters/Linkedin1.png' width='20' height='20' alt='#' style='display:block; vertical-align:middle;'></a>     </th>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <td align='center' height='1' width='10' style='font-size: 1px; line-height: 1px; width:10px;'>");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th>");
htmlText.append(" </th><td>                        <a href='https://www.youtube.com/c/Team_MSS' target='blank' style='color:#ef4048; text-decoration: none;'><img src='http://www.miraclesoft.com/images/newsletters/youtube1.png' width='20' height='20' alt='#' style='display:block; vertical-align:middle;'></a>     ");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               </td><td align='center' height='1' width='10' style='font-size: 1px; line-height: 1px; width:10px;'>");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th>");
htmlText.append(" </th><td>                        <a href='https://twitter.com/Team_MSS' target='blank' style='color:#ef4048; text-decoration: none;'><img src='http://www.miraclesoft.com/images/newsletters/Twitter1.png' width='20' height='20' alt='#' style='display:block; vertical-align:middle;'></a>     ");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               </td><td align='center' height='1' width='10' style='font-size: 1px; line-height: 1px; width:10px;'>");
htmlText.append("                                                                               </td>");
htmlText.append("                                                                               <!-- margin -->");
htmlText.append("                                                                               <th>");
htmlText.append("                                                                                 </th></tr>");
htmlText.append("                                                                         </tbody>");
htmlText.append("                                                                      </table>");
htmlText.append("                                                                   </td>");
htmlText.append("                                                                </tr>");
htmlText.append("                                                                <!-- icons -->");
htmlText.append("                                                             </tbody>");
htmlText.append("                                                          </table>");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                    <tr>");
htmlText.append("                                                       <td align='center' height='39' width='1' style='font-size: 1px;line-height: 20px;height: 20px;'>&nbsp;");
htmlText.append("                                                       </td>");
htmlText.append("                                                    </tr>");
htmlText.append("                                                    <!-- margin -->");
htmlText.append("                                                 </tbody>");
htmlText.append("                                              </table>");
htmlText.append("                                           </th>");
htmlText.append("                                           <!-- section -->");
htmlText.append("                                        </tr>");
htmlText.append("                                     </tbody>");
htmlText.append("                                  </table>");
htmlText.append("                               </td>");
htmlText.append("                            </tr>");
htmlText.append("                         </tbody>");
htmlText.append("                      </table>");
htmlText.append("                   </td>");
htmlText.append("                   <!--[if gte mso 9]>");
htmlText.append("                   </v:textbox>");
htmlText.append("                   </v:rect>");
htmlText.append("                   <![endif]-->");
htmlText.append("                </tr>");
htmlText.append("                <!--[if (gte mso 9)|(IE)]>");
htmlText.append("          </table>");
htmlText.append("          <![endif]-->");
htmlText.append("          </tbody>");
htmlText.append("       </table>");
htmlText.append("    ");
htmlText.append(" <span class='gr__tooltip'><span class='gr__tooltip-content'></span><i class='gr__tooltip-logo'></i><span class='gr__triangle'></span></span></body></html>");
                   
emailReq.setEmailContent(htmlText.toString());
emailReq.setEmailContentFormat("HTML");
                emailReq.setTextContent("TextContent");

                MessageFooter messageFooter = new MessageFooter();
                    messageFooter.setAddressLine1("45625 Grand River Avenue");
                messageFooter.setOrganizationName("Miracle Software Systems, Inc.");
                messageFooter.setCity("Novi");
                messageFooter.setCountry("US");
                messageFooter.setState("MI");
                messageFooter.setPostalCode("48374");
                emailReq.setMessageFooter(messageFooter);

      
                emailReq.setSentToContactLists(scl);


              //  System.out.println(emailReq.toJSON().toString());

                EmailCampaignResponse ecrq = ecs.addCampaign(emailReq);

                EmailCampaignScheduleService ecsh = new EmailCampaignScheduleService("dd48ad18-32cd-43ff-95db-6dae1119bb3f", "9u6qt7fjruawny4c6eevbxvp");

                 

                EmailCampaignSchedule Ecs = new EmailCampaignSchedule();
                
              //  Ecs.setScheduledDate("2017-03-07T23:32:00.486Z");
 //Ecs.setScheduledDate(DateUtility.getInstance().getCurrentESTTime());
              //  System.out.println("ecrq.getId()........." + ecrq.getId());
                //System.out.println(Ecs.toJSON());
//      EmailCampaignSchedule ecshh= ecsh.updateSchedule("1127025658399", "1", Ecs);
                EmailCampaignSchedule ecshh = ecsh.addSchedule(ecrq.getId(), Ecs);
              //  System.out.println(ecshh.getId());
              //  System.out.println(ecshh.getScheduledDate());


               // System.out.println(ecrq.getTemplateType());

            
        } catch (ConstantContactServiceException e) {
            ConstantContactServiceException c = (ConstantContactServiceException) e.getCause();
            for (Iterator<RawApiRequestError> i = c.getErrorInfo().iterator(); i.hasNext();) {
                RawApiRequestError item = i.next();
                System.out.println(item.getErrorKey() + " : " + item.getErrorMessage());
            }
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    } 
}
    


